version: '2.3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
  api:
    image: gleandroj/laravel:slim
    ports:
      - "80:80"
      - "4444:4444"
      - "8080:8080"
    volumes:
      - .:/home/deploy/app:Z
    depends_on:
      - db